### ISSUE TITLE
Scheduled update not working

### ISSUE THREAD

**Issue by oweppe** [gelin/weather-notification#60] opened 2020-07-03 07:45 UTC
Hi,

I noticed the auto-update is not running properly with 0.3.11:
The notification is displayed, but is never refreshed. 
Once I tap the notification, the popup window appears and the weather info is being refreshed almost instantly (proving this is not a communication issue with openweather).

Battery optimization disabled, backgroup running enabled, nothing seem to revive the scheduling.
 
Android 10 Samsung OneUI.

Thanks for this great app!

**Comment by birdwing** [comment] 2020-07-07 18:13
I believe the issue is with Location services.

Currently weather-notification on Android 10 does not ask for: "ACCESS_BACKGROUND_LOCATION"
So you can only set the location permission to "Allow only while the App is in use" or "Deny"

I'm not sure if the notification being displayed is enough for android to consider the app "In Use" for updating a users location.

So if you do not have a "Manual" location set, Weather Notification is not able to get your location, and therefore cannot update the weather.

**Comment by birdwing** [comment] 2020-07-07 19:28
I believe I have confirmed this

I am running a Google Pixed 3XL with Android 10
I have set _Battery Optimization_ for Weather Notifications to _Don't Optimize_.

The weather does not auto update if I have Weather Notifications __Detect Location__ set to _By GPS satallites_ or _By cellular or Wi-Fi network_.

If I change _Detect Location_ to _Manually_ and set a location, then the weather updates properly in the background.
This points to _Weather Notifications_ not being able to get a users location in the background.

I believe that __ACCESS_BACKGROUND_LOCATION__ must be added to the _manifest.xml_ file.

---
__If you don't know how to turn off Battery Optimization__

1. Open up android settings and go to _Apps & Notifications_
2. Tap on _Advanced_
3. Tap on _Special app access_
4. Tap on _Battery optimization_
5. The dropdown will default to _Not optimized_
    * This is a list of apps that are not optimized, meaning android will not limit their functionality to save battery when they are in the background.
    * Check to see if _Weather Notifications_ is on this list. If it is you are done. Otherwise continue to step 6.
6. Tap on the dropdown and change it to _All apps_.
7. Scroll down until you find _Weather Notifications_ and tap on it.
8. In the alert that pops up set it to _Don't Optimize_ and tap done.

**Comment by oweppe** [comment] 2020-07-07 19:33
Yes I can confirm too that the refresh works fine when I switch to manual location.

**Comment by jmlgo** [comment] 2020-07-22 10:48
Same for Xiaomi MIUI 12.
No ACCESS_BACKGROUND_LOCATION permission requested. Auto-update only works with manual location.

**Comment by gelin** [comment] 2020-08-15 10:19
Fixed here: https://github.com/gelin/weather-notification/commit/07614c698b564744c8f573e877a886bc6589b5d4

Going to be released in v0.3.13.

**Closed by gelin** 2020-08-15 10:19 UTC
